language: node_js
node_js:
  - "8"
services:
  - mongodb
install:
  - npm install --prefix server
  - npm install --prefix client
script:
  - npm run test-coverage --prefix server
  - npm run build --prefix client
after_success:
  - npm run coveralls --prefix server